import type { Metadata } from 'next';
import './styles/global.css';

export const metadata: Metadata = {
  title: 'PortaLink',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}